export class InMemoryDataService {
  createDb() {
    const heroes = [
    { id: 1, name: 'Steven "Steve" Grant Rogers', title: 'Captain America', origin: 'Earth',
    image: '../../assets/img/captain-america-card.jpg',
    avatar: '../../assets/img/captain-america-avatar.png', specie: 'Human', appearance: ['Captain America: The First Avenger', 'The Avengers', 'Thor: The Dark World', 'Captain America: The Winter Soldier', 'Avengers: Age of Ultron', 'Ant-Man', 'Captain America: Civil War', 'Spider-Man: Homecoming', 'Avengers: Infinity War'], cast: 'Christopher Robert Evans(Chris Evans)'},
    { id: 2, name: 'Margaret Elizabeth "Peggy" Carter', title: 'Agent Carter', origin: 'Earth',
    image: '../../assets/img/agent-carter-card.jpg',
    avatar: '../../assets/img/agent-carter-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger', 'Marvel One-Shot: Agent Carter', 'Captain America: The Winter Soldier', 'Avengers: Age of Ultron', 'Ant-Man'], cast: 'Hayley Elizabeth Atwell'},
    { id: 3, name: 'James Buchanan Barnes', title: 'Winter Soldier', origin: 'Earth', image: '../../assets/img/winter-soldier-card.jpg',
    avatar: '../../assets/img/winter-soldier-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger', 'Captain America: The Winter Soldier', 'Ant-Man', 'Captain America: Civil War', 'Black Panther', 'Avengers: Infinity War'], cast: 'Sebastian Stan'},
    { id: 4, name: 'Johann Schmidt', title: 'Red Skull', origin: 'Earth', image: '../../assets/img/red-skull-card.png',
    avatar: '../../assets/img/red-skull-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger', 'The Avengers*', 'Avengers: Infinity War'], cast: 'Hugo Wallace Weaving and Ross Marquand'},
    { id: 5, name: 'Howard Anthony Walter Stark', title: 'Howard Stark', origin: 'Earth', image: '../../assets/img/howard-stark-card.jpg',
    avatar: '../../assets/img/howard-stark-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger', 'Iron Man', 'Iron Man 2', 'Marvel One-Shot: Agent Carter', 'Captain America: The Winter Soldier', 'Ant-Man', 'Captain America: Civil War']},
    { id: 6, name: 'General Chester Richard  Phillips', title: 'General Phillips', origin: 'Earth', image: '../../assets/img/chester-phillips-card.jpg',
    avatar: '../../assets/img/chester-phillips-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger'], cast: 'Tommy Lee Jones'},
    { id: 7, name: 'Timothy Aloysius Cadwallader "Dum Dum" Dugan', title: 'Dum Dum Dugan', origin: 'Earth', image: '../../assets/img/dum-dum-dugan-card.jpg',
    avatar: '../../assets/img/dum-dum-dugan-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger', 'Marvel One-Shot: Agent Carter'], cast: 'Neal P. McDonough'},
    { id: 8, name: 'Gabriel "Gabe" Jones', title: 'Gabe Jones', origin: 'Earth', image: '../../assets/img/gabe-card.jpg',
    avatar: '../../assets/img/gabe-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger'], cast: 'Derek Luke'},
    { id: 9, name: 'Dr. Abraham Erskine', title: 'Dr. Erskine', origin: 'Earth', image: '../../assets/img/erskine-card.jpg',
    avatar: '../../assets/img/erskine-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger'], cast: 'Stanley Tucci'},
    { id: 10, name: 'Dr. Arnim Zola', title: 'Arnim Zola', origin: 'Earth', image: '../../assets/img/arnim-zola-card.jpg',
    avatar: '../../assets/img/arnim-zola-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger', 'Captain America: The Winter Soldier', 'Ant-Man*'], cast: 'Toby Jones'},
    { id: 11, name: 'James "Jim" Morita', title: 'Jim Morita', origin: 'Earth', image: '../../assets/img/jim-morita-card.jpg',
    avatar: '../../assets/img/jim-morita-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger'], cast: 'Kenneth Choi'},
    { id: 12, name: 'Heinz Kruger', title: 'Heinz Kruger', origin: 'Earth', image: '../../assets/img/heinz-kruger-card.jpg',
    avatar: '../../assets/img/heinz-kruger-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger'], cast: 'Richard Armitage'},
    { id: 13, name: 'Joseph "Joey" Chapman', title: 'Union Jack', origin: 'Earth', image: '../../assets/img/union-jack-card.jpg',
    avatar: '../../assets/img/union-jack-avatar.png', specie: 'Human', appearance: ['Captain America: The First Avenger'], cast: 'John Joseph Feild'},
    { id: 14, name: 'Nicholas Joseph "Nick" Fury', title: 'Agent Fury', origin: 'Earth', image: '../../assets/img/nick-fury-card.jpg',
    avatar: '../../assets/img/nick-fury-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger', 'Iron Man', 'Iron Man 2', 'Thor', 'The Avengers', 'Iron Man 3', 'Captain America: The Winter Soldier', 'Avengers: Age of Ultron', 'Avengers: Infinity War', 'Captain Marvel'], cast: 'Samuel Leroy Jackson'},
    { id: 15, name: 'Anthony Edward "Tony" Stark', title: 'Iron Man', origin: 'Earth', image: '../../assets/img/iron-man-card.jpg',
    avatar: '../../assets/img/iron-man-avatar.png', specie: 'Human', appearance: ['Iron Man', 'The Incredible Hulk', 'Iron Man 2', 'The Avengers', 'Iron Man 3', 'Avengers: Age of Ultron', 'Captain America: Civil War', 'Spider-Man: Homecoming', 'Avengers: Infinity War'], cast: 'Robert John Downey Jr.'},
    { id: 16, name: 'Virginia "Pepper" Potts', title: 'Iron Woman', origin: 'Earth', image: '../../assets/img/iron-woman-card.jpg',
    avatar: '../../assets/img/iron-woman-avatar.jpg', specie: 'Human', appearance: ['Iron Man', 'Iron Man 2', 'The Avengers', 'Iron Man 3', 'Avengers: Age of Ultron', 'Captain America: Civil War', 'Spider-Man: Homecoming', 'Avengers: Infinity War'], cast: 'Gwyneth Kate Paltrow'},
    { id: 17, name: 'Obadiah Stane', title: 'Iron Monger', origin: 'Earth', image: '../../assets/img/iron-monger-card.jpg',
    avatar: '../../assets/img/iron-monger-avatar.png', specie: 'Human', appearance: ['Iron Man'], cast: 'Jeff Bridges'},
    { id: 18, name: 'James "Jim" Rupert Rhodes', title: 'War Machine', origin: 'Earth', image: '../../assets/img/war-machine-card.jpg',
    avatar: '../../assets/img/war-machine-avatar.png', specie: 'Human', appearance: ['Iron Man', 'Iron Man 2', 'The Avengers', 'Iron Man 3', 'Avengers: Age of Ultron', 'Captain America: Civil War', 'Avengers: Infinity War'], cast: 'Donald Frank Cheadle Jr and Terrence Dashon Howard'},
    { id: 19, name: 'Harold Joseph "Happy" Hogan', title: 'Happy Hogun', origin: 'Earth', image: '../../assets/img/happy-hogan-card.jpg',
    avatar: '../../assets/img/happy-hogan-avatar.jpg', specie: 'Human', appearance: ['Iron Man', 'Iron Man 2', 'Iron Man 3', 'Spider-Man: Homecoming'], cast: 'Jonathan Kolia Favreau(Jon Favreau)'},
    { id: 20, name: 'Professor Ho Yinsen', title: 'Ho Yinsen', origin: 'Earth', image: '../../assets/img/ho-yinsen-card.png',
    avatar: '../../assets/img/ho-yinsen-avatar.jpg', specie: 'Human', appearance: ['Iron Man', 'Iron Man 3'], cast: 'Shaun Toub'},
    { id: 21, name: 'Edwin Jarvis', title: 'J.A.R.V.I.S.', origin: 'Earth', image: '../../assets/img/jarvis-card.jpg',
    avatar: '../../assets/img/jarvis-avatar.jpg', specie: 'A.I. Program', appearance: ['Iron Man', 'Iron Man 2', 'The Avengers', 'Iron Man 3', 'Avengers: Age of Ultron'], cast: 'Paul Bettany'},
    { id: 22, name: 'Christine Everhart', title: 'Christine Everhart', origin: 'Earth', image: '../../assets/img/christine-everhart-card.jpg',
    avatar: '../../assets/img/christine-everhart-avatar.jpg', specie: 'Human', appearance: ['Iron Man', 'Iron Man 2'], cast: 'Leslie Bibb'},
    { id: 23, name: 'Phillip J. "Phil" Coulson', title: 'Agent Coulson', origin: 'Earth', image: '../../assets/img/coulson-card.jpg',
    avatar: '../../assets/img/coulson-avatar.jpg', specie: 'Human', appearance: ['Captain America: The First Avenger', 'Iron Man', 'Iron Man 2', 'Thor', 'Marvel One-Shot: The Consultant', 'Marvel One-Shot: A Funny Thing Happened on the Way to Thor\'s Hammer', 'The Avengers', 'Captain Marvel'], cast: 'Robert Clark Gregg'},
    { id: 24, name: 'Robert Bruce Banner', title: 'Hulk', origin: 'Earth', image: '../../assets/img/hulk-card.jpg',
    avatar: '../../assets/img/hulk-avatar.png', specie: 'Human', appearance: ['The Incredible Hulk', 'The Avengers', 'Iron Man 3', 'Avengers: Age of Ultron', 'Thor: Ragnarok', 'Avengers: Infinty War'], cast: 'Mark Alan Ruffalo and Edward Harrison Norton'},
    { id: 25, name: 'Emil Blonsky', title: 'Abomination', origin: 'Earth', image: '../../assets/img/abomination-card.jpg',
    avatar: '../../assets/img/abomination-avatar.jpg', specie: 'Human', appearance: ['The Incredible Hulk', 'Avengers: Age of Ultron*'], cast: 'Simon Timothy Roth(Tim Roth)'},
    { id: 26, name: 'Elizabeth "Betty" Ross Talbot Banner', title: 'Red She-Hulk', origin: 'Earth', image: '../../assets/img/betty-ross-card.jpg',
    avatar: '../../assets/img/betty-ross-avatar.jpg', specie: 'Human', appearance: ['The Incredible Hulk', 'Avengers: Infinity War*'], cast: 'Liv Rundgren Tyler'},
    { id: 27, name: 'General Thaddeus E. "Thunderbolt" Ross', title: 'Red Hulk', origin: 'Earth', image: '../../assets/img/thaddeus-ross-card.jpg',
    avatar: '../../assets/img/thaddeus-ross-avatar.jpg', specie: 'Human', appearance: ['The Incredible Hulk', 'Marvel One-Shot: The Consultant', 'Captain America: Civil War', 'Avengers: Infinity War'], cast: 'William McChord Hurt'},
    { id: 28, name: 'Samuel Sterns', title: 'The Leader', origin: 'Earth', image: '../../assets/img/samuel-sterns-card.jpg',
    avatar: '../../assets/img/samuel-sterns-avatar.jpg', specie: 'Human', appearance: ['The Incredible Hulk'], cast: 'Timothy "Tim" Blake Nelson'},
    { id: 29, name: 'Dr. Leonard "Leo" Samson', title: 'Doc Samson', origin: 'Earth', image: '../../assets/img/samson-card.jpg',
    avatar: '../../assets/img/samson-avatar.jpg', specie: 'Human', appearance: ['The Incredible Hulk'], cast: 'Tyler Gerald Burrell'},
    { id: 30, name: 'Natalia Alianovna "Natasha" Romanova', title: 'Black Widow', origin: 'Earth', image: '../../assets/img/black-widow-card.jpg',
    avatar: '../../assets/img/black-widow-avatar.png', specie: 'Human', appearance: ['Iron Man 2', 'Thor', 'The Avengers', 'Captain America: The Winter Soldier', 'Avengers: Age of Ultron', 'Captain America: Civil War', 'Avengers: Infinity War'], cast: 'Scarlett Ingrid Johansson'},
    { id: 31, name: 'Ivan Antonovich Vanko', title: 'Whiplash', origin: 'Earth', image: '../../assets/img/whiplash-card.jpg',
    avatar: '../../assets/img/whiplash-avatar.jpg', specie: 'Human', appearance: ['Iron Man 2'], cast: 'Philip Andre "Mickey" Rourke Jr(Mickey Rourke)'},
    { id: 32, name: 'Justin Hammer', title: 'Justin Hammer', origin: 'Earth', image: '../../assets/img/justin-hammer-card.jpg',
    avatar: '../../assets/img/justin-hammer-avatar.jpg', specie: 'Human', appearance: ['Iron Man 2', 'Marvel One-Shot: All the Hail King'], cast: 'Sam Rockwell'},
    { id: 33, name: 'Thor Odinson', title: 'Thor', origin: 'Asgard', image: '../../assets/img/thor-card.jpg',
    avatar: '../../assets/img/thor-avatar.png', specie: 'Asgardian', appearance: ['Thor', 'The Avengers', 'Thor: The Dark World', 'Avengers: Age of Ultron', 'Doctor Strange', 'Thor: Ragnarok', 'Avengers: Infinity War'], cast: 'Christopher "Chris" Hemsworth'},
    { id: 34, name: 'Loki Laufeyson', title: 'Loki', origin: 'Jotunheim', image: '../../assets/img/loki-card.jpg',
    avatar: '../../assets/img/loki-avatar.jpeg', specie: 'Frost Giant', appearance: ['Thor', 'The Avengers', 'Thor: The Dark World', 'Avengers: Age of Ultron', 'Thor: Ragnarok', 'Avengers: Infinity War'], cast: 'Thomas William Hiddleston'},
    { id: 35, name: 'Jane Foster', title: 'The Mortal', origin: 'Earth', image: '../../assets/img/jane-foster-card.png',
    avatar: '../../assets/img/jane-foster-avatar.jpg', specie: 'Human', appearance: ['Thor', 'The Avengers', 'Thor: The Dark World', 'Avengers: Age of Ultron*', 'Thor: Ragnarok*'], cast: 'Natalie Portman'},
    { id: 36, name: 'Odin Borson', title: 'Odin', origin: 'Asgard', image: '../../assets/img/odin-card.jpg',
    avatar: '../../assets/img/odin-avatar.jpg', specie: 'Asgardian', appearance: ['Thor', 'Thor: The Dark World', 'Thor: Ragnarok'], cast: 'Sir Philip Anthony Hopkins'},
    { id: 37, name: 'Hiemdall', title: 'Hiemdall', origin: 'Asgard', image: '../../assets/img/heimdall-card.jpg',
    avatar: '../../assets/img/heimdall-avatar.jpg', specie: 'Asgardian', appearance: ['Thor', 'Thor: The Dark World', 'Avengers: Age of Ultron', 'Thor: Ragnarok', 'Avengers: Infinity War'], cast: 'Idrissa Akuna Elba OBE'},
    { id: 38, name: 'Lady Sif', title: 'Sif', origin: 'Asgard', image: '../../assets/img/sif-card.jpg',
    avatar: '../../assets/img/sif-avatar.jpg', specie: 'Asgardian', appearance: ['Thor', 'Thor: The Dark World'], cast: 'Jaimie Lauren Alexander'},
    { id: 39, name: 'Frigga Freyrdottir', title: 'Frigga', origin: 'Asgard', image: '../../assets/img/frigga-card.jpg',
    avatar: '../../assets/img/frigga-avatar.jpg', specie: 'Asgardian', appearance: ['Thor', 'Thor: The Dark World'], cast: 'Rene Marie Russo'},
    { id: 40, name: 'Volstagg', title: 'Volstagg', origin: 'Asgard', image: '../../assets/img/volstagg-card.jpg',
    avatar: '../../assets/img/volstagg-avatar.jpg', specie: 'Asgardian', appearance: ['Thor', 'Thor: The Dark World', 'Thor: Ragnarok'], cast: 'George Raymond Stevenson'},
    { id: 41, name: 'Hogun', title: 'Hogun the Grim', origin: 'Asgard', image: '../../assets/img/hogun-card.jpg',
    avatar: '../../assets/img/hogun-avatar.jpg', specie: 'Asgardian', appearance: ['Thor', 'Thor: The Dark World', 'Thor: Ragnarok'], cast: 'Joshua Paul Dallas and Zachary Levi Pugh(Zachary Levi)'},
    { id: 42, name: 'Fandrall', title: 'Fandrall', origin: 'Asgard', image: '../../assets/img/fandrall-card.jpg',
    avatar: '../../assets/img/fandrall-avatar.jpg', specie: 'Asgardian', appearance: ['Thor', 'Thor: The Dark World', 'Thor: Ragnarok'], cast: 'Joshua Paul Dallas and Zachary Levi Pugh(Zachary Levi)'},
    { id: 43, name: 'Laufey', title: 'Laufey', origin: 'Jotunheim', image: '../../assets/img/laufey-card.jpg',
    avatar: '../../assets/img/laufey-avatar.jpg', specie: 'Forst Giant', appearance: ['Thor'], cast: 'Colm Feore'},
    { id: 44, name: 'Destroyer', title: 'Destroyer', origin: 'Asgard', image: '../../assets/img/destroyer-card.jpg',
    avatar: '../../assets/img/destroyer-avatar.jpg', specie: 'Weapon', appearance: ['Thor'], cast: '--No one--'},
    { id: 45, name: 'Clinton Francis "Clint" Barton', title: 'Hawkeye', origin: 'Earth', image: '../../assets/img/hawkeye-card.jpg',
    avatar: '../../assets/img/hawkeye-avatar.png', specie: 'Human', appearance: ['Thor', 'The Avengers', 'Avengers: Age of Ultron', 'Captain America: Civil War'], cast: 'Jeremy Lee Renner'},
    { id: 46, name: 'Jasper Sitwell', title: 'Jasper Sitwell', origin: 'Earth', image: '../../assets/img/sitwell-card.jpg',
    avatar: '../../assets/img/sitwell-avatar.jpg', specie: 'Human', appearance: ['Thor', 'Marvel One-Shot: The Consultant', 'Marvel One-Shot: Item 47', 'Captain America: The Winter Soldier'], cast: 'Maximiliano Hernández'},
    { id: 47, name: 'Commander Maria Hill', title: 'Agent Hill', origin: 'Earth', image: '../../assets/img/maria-hill-card.jpg',
    avatar: '../../assets/img/maria-hill-avatar.jpg', specie: 'Human', appearance: ['The Avengers', 'Captain America: The Winter Soldier', 'Avengers: Age of Ultron', 'Avengers: Infinity War'], cast: 'Jacoba Francisca Maria "Cobie" Smulders'},
    { id: 48, name: 'The Other', title: 'Chayton', origin: 'Earth', image: '../../assets/img/the-other-card.jpg',
    avatar: '../../assets/img/the-other-avatar.jpg', specie: 'Demon/Elder Gods', appearance: ['The Avengers', 'Guardians of the Galaxy Vol. 1'], cast: 'Alexis Denisof'},
    { id: 49, name: 'Thanos', title: 'Thanos', origin: 'Titan', image: '../../assets/img/thanos-card.jpg',
    avatar: '../../assets/img/thanos-avatar.jpg', specie: 'Eternal-Deviant Hybrid', appearance: ['The Avengers', 'Guardians of the Galaxy Vol. 1', 'Guardians of the Galaxy Vol. 2', 'Avengers: Age of Ultron', 'Avengers: Infinity War'], cast: 'Damion Poitier and Josh James Brolin'},
    { id: 50, name: 'James "Jim" Rupert Rhodes', title: 'Iron Patriot', origin: 'Earth', image: '../../assets/img/iron-patriot-card.jpg',
    avatar: '../../assets/img/iron-patriot-avatar.jpg', specie: 'Human', appearance: ['Iron Man 3'], cast: 'Donald Frank Cheadle Jr'},
    { id: 51, name: 'Trevor Slattery', title: 'The Mandarin', origin: 'Earth', image: '../../assets/img/mandarin-card.jpg',
    avatar: '../../assets/img/mandarin-avatar.jpg', specie: 'Human', appearance: ['Iron Man 3', 'Marvel One-Shot: All the Hail King', 'Ant-Man*'], cast: 'Sir Ben Kingsley'},
    { id: 52, name: 'Aldrich Killian', title: 'Aldrich Killian', origin: 'Earth', image: '../../assets/img/killian-card.jpg',
    avatar: '../../assets/img/killian-avatar.jpg', specie: 'Human', appearance: ['Iron Man 3'], cast: 'Sir Ben Kingsley'},
    { id: 53, name: 'Maya Hansen', title: 'Maya Hansen', origin: 'Earth', image: '../../assets/img/maya-hansen-card.jpg',
    avatar: '../../assets/img/maya-hansen-avatar.jpg', specie: 'Human', appearance: ['Iron Man 3'], cast: 'Rebecca Maria Hall'},
    { id: 54, name: 'Harley Keener', title: 'Harley Keener', origin: 'Earth', image: '../../assets/img/harley-keener-card.jpg',
    avatar: '../../assets/img/harley-keener-avatar.jpg', specie: 'Human', appearance: ['Iron Man 3'], cast: 'Ty Simpkin'},
    { id: 55, name: 'Savin', title: 'Coldblood-7', origin: 'Earth', image: '../../assets/img/coldblood-card.jpg',
    avatar: '../../assets/img/coldblood-avatar.jpg', specie: 'Human', appearance: ['Iron Man 3'], cast: 'James Badgett "Badge" Dale'},
    { id: 56, name: 'Ellen Brandt', title: 'Ellen Brandt', origin: 'Earth', image: '../../assets/img/brandt-card.jpg',
    avatar: '../../assets/img/brandt-avatar.jpg', specie: 'Human', appearance: ['Iron Man 3'], cast: 'Stéphanie Szostak'},
    { id: 57, name: 'Jack Taggart', title: 'Firepower', origin: 'Earth', image: '../../assets/img/firepower-card.jpg',
    avatar: '../../assets/img/firepower-avatar.png', specie: 'Human', appearance: ['Iron Man 3'], cast: 'Ashley Gerge Hamilton'},
    { id: 58, name: 'Malekith', title: 'Malekith the Accursed', origin: 'Svartalfhiem', image: '../../assets/img/malekith-card.jpg',
    avatar: '../../assets/img/malekith-avatar.jpg', specie: 'Dark Elf', appearance: ['Thor: The Dark World'], cast: 'Christopher Eccleston'},
    { id: 59, name: 'Kurse', title: 'Dark Elf Algrim the Strong', origin: 'Svartalfhiem', image: '../../assets/img/kurse-card.jpg',
    avatar: '../../assets/img/kurse-avatar.png', specie: 'Dark Elf', appearance: ['Thor: The Dark World'], cast: 'Adewale Akinnuoye-Agbaje'},
    { id: 60, name: 'Tyr', title: 'Tyr', origin: 'Asgard', image: '../../assets/img/tyr-card.jpg',
    avatar: '../../assets/img/tyr-avatar.jpg', specie: 'Asgardian', appearance: ['Thor: The Dark World'], cast: 'Clive Russel'},
    { id: 61, name: 'Taneleer Tivan', title: 'Collector', origin: 'Cygnus X-1', image: '../../assets/img/collector-card.jpg',
    avatar: '../../assets/img/collector-avatar.jpg', specie: 'Cygnusian', appearance: ['Thor: The Dark World', 'Guardians of the Galaxy Vol. 1', 'Avengers: Infinity War'], cast: 'Benicio Monserrate Rafael del Toro Sánchez'},
    { id: 62, name: 'Carina Tivan', title: 'Carina Tivan', origin: 'Cygnus X-1', image: '../../assets/img/carina-card.jpg',
    avatar: '../../assets/img/carina-avatar.jpg', specie: 'Cygnusian', appearance: ['Thor: The Dark World', 'Guardians of the Galaxy Vol. 1'], cast: 'Ophelia Lucy Lovibond'},
    { id: 63, name: 'Sam Wilson', title: 'Falcon', origin: 'Earth', image: '../../assets/img/falcon-card.jpg',
    avatar: '../../assets/img/falcon-avatar.jpg', specie: 'Human', appearance: ['Captain America: The Winter Soldier', 'Avengers: Age of Ultron', 'Ant-Man', 'Captain America: Civil War', 'Avengers: Infinity War'], cast: 'James Badgett "Badge" Dale'},
    // { id: 46, name: 'Sharon Carter', title: 'Agent Sharon', origin: 'Earth', image: '../../assets/img/sharon-carter-card.jpg',
    // avatar: '../../assets/img/sharon-carter-avatar.jpg'}, 
    // { id: 47, name: 'Brock Rumlow', title: 'Crossbones', origin: 'Earth', image: '../../assets/img/crossbones-card.jpg',
    // avatar: '../../assets/img/crossbones-avatar.jpg'}, 
    // { id: 48, name: 'Georges Batroc', title: 'Batroc the Leaper', origin: 'Earth', image: '../../assets/img/leaper-card.jpg',
    // avatar: '../../assets/img/leaper-avatar.jpg'}, 
    // { id: 49, name: 'Wanda Maximoff', title: 'Scarlet Witch', origin: 'Earth', image: '../../assets/img/scarlet-witch-card.jpg',
    // avatar: '../../assets/img/scarlet-witch-avatar.jpg'}, 
    // { id: 50, name: 'Pietro Django Maximoff', title: 'Quick Silver', origin:'Earth', image: '../../assets/img/quicksilver-card.jpg',
    // avatar: '../../assets/img/quicksilver-avatar.jpg'},
    // { id: 51, name: 'Baron Strucker', title: 'Baron Strucker', origin:'Earth', image: '../../assets/img/strucker-card.jpg',
    // avatar: '../../assets/img/strucker-avatar.jpg'},
    // { id: 52, name: 'Gamora Zen Whoberi Ben Titan', title: 'Gamora', origin:'Titan', image: '../../assets/img/gamora-card.jpg',
    // avatar: '../../assets/img/gamora-avatar.jpg'},  
    // { id: 53, name: 'Groot', title: 'Groot', origin:'Titan', image: '../../assets/img/groot-card.jpg',
    // avatar: '../../assets/img/groot-avatar.jpg'},
    // { id: 54, name: 'Drax', title: 'Drax The Destroyer', origin:'Titan', image: '../../assets/img/drax-card.jpg',
    // avatar: '../../assets/img/drax-avatar.jpg'},
    // { id: 55, name: 'Yondu', title: 'Yondu', origin:'Titan', image: '../../assets/img/yondu-card.jpg',
    // avatar: '../../assets/img/yondu-avatar.jpg'},
    // { id: 56, name: 'Howard', title: 'Howard the Duck', origin:'Titan', image: '../../assets/img/howard-the-duck-card.jpg',
    // avatar: '../../assets/img/howard-the-duck-avatar.jpg'},
    // { id: 57, name: 'Cosmo', title: 'Cosmo the Space Dog', origin:'Titan', image: '../../assets/img/cosmo-card.jpg',
    // avatar: '../../assets/img/cosmo-avatar.jpg'},
    // { id: 58, name: 'Kraglin', title: 'Kraglin', origin:'Titan', image: '../../assets/img/kraglin-card.jpg',
    // avatar: '../../assets/img/kraglin-avatar.jpg'},
    // { id: 59, name: 'Corpsman Dey', title: 'Corpsman Dey', origin:'Xandar', image: '../../assets/img/corpsman-dey-card.jpg',
    // avatar: '../../assets/img/corpsman-dey-avatar.jpg'},
    // { id: 60, name: 'Mainframe', title: 'Mainframe', origin:'Titan', image: '../../assets/img/mainframe.jpg',
    // avatar: '../../assets/img/mainframe.jpg'},
    // { id: 61, name: 'Groot', title: 'Baby Groot', origin:'Titan', image: '../../assets/img/baby-groot-card.jpg',
    // avatar: '../../assets/img/baby-groot-avatar.jpg'},
    // { id: 62, name: 'Kismet', title: 'Ayesha', origin:'Titan', image: '../../assets/img/ayesha-card.jpg',
    // avatar: '../../assets/img/ayesha-avatar.jpg'},
    // { id: 63, name: 'Aleta Ogord', title: 'Aleta Ogord', origin:'Titan', image: '../../assets/img/aleta-card.jpg',
    // avatar: '../../assets/img/aleta-avatar.jpg'},
    // { id: 64, name: 'Charlie 27', title: 'Charlie 27', origin:'Titan', image: '../../assets/img/charlie-27-card.jpg',
    // avatar: '../../assets/img/charlie-27-avatar.jpg'},
    // { id: 65, name: 'Ultron', title: 'Ultron', origin:'Earth', image: '../../assets/img/ultron-card.jpg',
    // avatar: '../../assets/img/ultron-avatar.jpg'}
    ];

// ,
//     { id: 17, name: 'Vision', title: 'Vision', origin:'Earth', image: '../../assets/img/captain-america.jpg',
//      avatar: '../../assets/img/agent-carter-avatar.jpg'},
return {heroes};
}
}
